/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "contador.h"

result *
get_words_quantity_100(argp, rqstp)
	params *argp;
	struct svc_req *rqstp;
{

	static result  result;

	/*
	 * insert server code here
	 */

	return(&result);
}
