/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CONTADOR_H_RPCGEN
#define _CONTADOR_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>


struct params {
	struct {
		u_int dados_len;
		char *dados_val;
	} dados;
	struct {
		u_int palavras_len;
		char *palavras_val;
	} palavras;
};
typedef struct params params;
#ifdef __cplusplus
extern "C" bool_t xdr_params(XDR *, params*);
#elif __STDC__
extern  bool_t xdr_params(XDR *, params*);
#else /* Old Style C */
bool_t xdr_params();
#endif /* Old Style C */


struct result {
	int ocorrencias;
	int cont;
};
typedef struct result result;
#ifdef __cplusplus
extern "C" bool_t xdr_result(XDR *, result*);
#elif __STDC__
extern  bool_t xdr_result(XDR *, result*);
#else /* Old Style C */
bool_t xdr_result();
#endif /* Old Style C */


#define PROG ((rpc_uint)55555555)
#define VERSAO ((rpc_uint)100)

#ifdef __cplusplus
#define GET_WORDS_QUANTITY ((rpc_uint)1)
extern "C" result * get_words_quantity_100(params *, CLIENT *);
extern "C" result * get_words_quantity_100_svc(params *, struct svc_req *);

#elif __STDC__
#define GET_WORDS_QUANTITY ((rpc_uint)1)
extern  result * get_words_quantity_100(params *, CLIENT *);
extern  result * get_words_quantity_100_svc(params *, struct svc_req *);

#else /* Old Style C */
#define GET_WORDS_QUANTITY ((rpc_uint)1)
extern  result * get_words_quantity_100();
extern  result * get_words_quantity_100_svc();
#endif /* Old Style C */

#endif /* !_CONTADOR_H_RPCGEN */
