/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "contador.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

result *
get_words_quantity_100(argp, clnt)
	params *argp;
	CLIENT *clnt;
{
	static result clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, GET_WORDS_QUANTITY, xdr_params, argp, xdr_result, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}
